#!/bin/sh
PID=/var/run/gunicorn.pid

if [ -f $PID ]; then rm $PID; fi

cd /code
gunicorn $APP_NAME:$APP_CALLABLE -k $GUNICORN_WORKER_TYPE -w $GUNICORN_WORKERS -t $GUNICORN_TIMEOUT -b unix:/tmp/gunicorn.sock --pid=$PID $GUNICORN_CLI_EXTEND
